services:
  bot:
    build: .
    image: 3xui-tgbot:latest
    container_name: 3xui-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    stop_grace_period: 20s
    networks:
      - bot-net

networks:
  bot-net:
    driver: bridge
